### ISSUE TITLE
GET: /quarto-render/ (404: Not Found) after installing 

### ISSUE THREAD

**Issue by maria-pro** [schochastics/academicons#1]
Hi,

I installed your extension as suggested but now I am seeing this error in RStudio when I save and render my qmd fle

```
"Error in utils::download.file(paste0("http://localhost:", port, "/quarto-render/"),  : 
cannot open URL 'http://localhost:6076/quarto-render/'"
```

I reinstalled quarto and now see this error in the Terminal:

`GET: /quarto-render/ (404: Not Found)`

**Comment by schochastics** [comment]
This sounds more like a general issue with quarto. Can you try render a document without the extension and see if that works?
