### ISSUE TITLE
Sizing issue

### ISSUE THREAD

**Issue by atsyplenkov** [schochastics/academicons#4]
Hi! I found that the sizing option is not working perfectly. Actually, the only literal sizing is returning an expected result. See an example below:

I am using quarto version `1.0.38`

![firefox_L0qAiTRZSW](https://user-images.githubusercontent.com/34775595/185406694-ccbe94c6-0583-4cf3-a122-fd81bcf5e066.png){width="50%"}

````
---
title: "Test"
toc: true
format: html
---

## Font Awesome
All examples should be equal to `2em`. They are.

`size=2xl` {{< fa battery-half size=2xl >}}
`size=2x ` {{< fa battery-half size=2x >}}
`size=huge` {{< fa battery-half size=huge >}}

## Academic Icons
All examples should be equal to `2em`. They are not…

`size=2xl` {{< ai google-scholar size=2xl >}}
`size=2x` {{< ai google-scholar size=2x >}}
`size=huge` {{< ai google-scholar size=huge >}}

## Academic Icons
Comparison of `2xl` (left) and `xl` (right). They are equal…

`size=2xl` {{< ai google-scholar size=2xl >}}
`size=xl` {{< ai google-scholar size=2xl >}}
````

**Comment by schochastics** [comment]
Thanks for pointing it out. Should be fixed now. Please reopen if it still doesnt work on your end
